:PROPERTIES:
:ID:       42f1429e-8a1b-4a94-8d6d-06865bc0ae89
:END:
#+title: Learning Curriculum

My idea is to learn Data Science as soon as I can, by reading the most recommended books and practicing as much as I can. To be more organized, I'll make a "learning timeline" table, where I'll write the most important things I learned by day and the sources where I got that information (so I can get back to them if I need it).

I have a strong Python and math foundation, so it won't be part of the learning path, and I can concentrate in other tools and concepts that I don't know or I haven't mastered yet.

This is the suggested structure for the "learning timeline", which I can change if I consider it a good idea:


| Day | Topic         | Confidence (0-5) | Source |
|-----+---------------+------------------+--------|
|   1 | Example Topic |                5 | None   |
|   2 |               |                  |        |


The table should be at the end of this readme file.

| Day | Topic         | Confidence (0-5) | Source |
|-----+---------------+------------------+--------|
|   1 | Example Topic |                5 | None   |
|   2 |               |                  |        |
